version: "3.8"
services:
  gateway:
    image: my-registry/my-msa-project/gateway:latest
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
    environment:
      - NODE_ENV=production

  auth:
    image: my-registry/my-msa-project/auth:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production

  event:
    image: my-registry/my-msa-project/event:latest
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production
# mongo, volumes 등은 기본 파일을 그대로 사용함.
